apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce  #can be used by a single node, other values possible are ReadOnlyMany,ReadWriteMany
  resources:
    requests:
      storage: 2Gi           #when the PV will be attached to a Pod, then Pod will request for 2Gb memory to Kubernetes
  